dist: trusty

language: java
jdk: oraclejdk8

before_script:
- curl https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg | sudo apt-key add -
- echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
- sudo apt-get update
- sudo apt-get install bazel

script:
- bazel test --test_output=all //src/test:unit
